apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: frontend
spec:
  selector:
    matchLabels:
      app: webapi
  template:
    metadata:
      labels:
        app: webapi
        component: frontend
    spec:
      containers:
      - name: webapi
        image: srswebapiimageregistry.azurecr.io/webapi
        ports:
        - containerPort: 8080